### ISSUE TITLE
Set a default status new everytime updating a Journal

### ISSUE THREAD

**Issue by iqbalbaharum** [iqbalbaharum/bekreno#30]
**Is your feature request related to a problem? Please describe.**
Every journal written by the user, would be read by the admin and mark as read once it has completed. Currently there is no edit features for the journal which make it impossible for user to update their journal through the UI. 

This is to prevent from user to change their journal after admin has read the journal.

**Describe the solution you'd like**
1. On journal update request, change the journal `status` to `updated`
2. On new notes added to the journal, change the journal `status` to `updated`

Endpoints
`PATCH /journal`
`POST /journal/{id}/comments`

**Comment by iqbalbaharum** [comment]
Test case:

1. POST /journal - New journal, status === 'new'
2. PATCH /journal/{id} - Updated journal, status === 'review'
3. PATCH /journal/{id} - Description updated, status === 'new'
4. PATCH /journal/{id} - Updated journal, status === 'review'
5. POST /journal/{id}/comments - Comment added, status === 'new'

**Comment by zh6ziq** [comment]
Correct me if I'm wrong. The correct endpoint for patching journals is `PATCH /journal/{id}` right? Because `PATCH /journal` might patch all the journal inside the database, while `PATCH /journal/{id}` will patch the journal based on its `id`

**Comment by aktaktaw** [comment]
I saw that the data type of status is using String, wouldn't be better we use integer so that it easier to compare like following below: 
0 = open case
1 = open case edited
2  = close case
