### ISSUE TITLE
Create Newsfeed

### ISSUE THREAD

**Issue by iqbalbaharum** [iqbalbaharum/bekreno#34]
**Is your feature request related to a problem? Please describe.**
As a user, centralize notifications would help in identifying a new updates of the system.

**Describe the solution you'd like**
Create newsfeed features

**Comment by Muazhero61** [comment]
Encik Iqbal,

To my understanding for this issue, is the issue similar to like create new user where can solve this by using endpoint ```POST/newsfeed```

If any, do make comment for further disccusion.
